# Generated by Django 4.2.6 on 2023-10-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_rename_thing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
