# Generated by Django 4.2.6 on 2023-10-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0004_alter_logentry_user'),
        ('things', '0005_remove_user_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Thing',
        ),
    ]
