# Generated by Django 4.2.6 on 2023-10-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0006_rename_user_thing'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
